language: node_js
node_js:
  - 10.6.0
script:
  - echo "Deploying for you John, make good choices!"
install:
  - npm install -g firebase-tools
after_success:
  - npm run build
  - firebase deploy --token $FIREBASE_TOKEN
branches:
  only:
    - master