language: node_js
node_js:
  - 10.6.0
install:
  - npm install -g firebase-tools
  - npm install -g react-scripts
script:
  - echo "Deploying for you John, make good choices!"
  - npm run build
  - firebase deploy --token $FIREBASE_TOKEN
branches:
  only:
    - master